### ISSUE TITLE
[doc] 4.2.2  Transitioning from Docker to CRI-O

### ISSUE THREAD

**Issue by jandubois** [SUSE/doc-caasp#528]
4.2.2  Transitioning from Docker to CRI-O

https://documentation.suse.com/suse-caasp/4/single-html/caasp-deployment/#_transitioning_from_docker_to_cri_o

As far as I can tell the option is not called `--strict-cap-defaults`, but `--strict-capability-defaults`.

See https://github.com/SUSE/skuba/pull/529/commits/c2f84394cf1cf4342847eeacabcc91980e31ebce

**Comment by r0ckarong** [comment]
@tdaines42 @ereslibre This parameter is not documented in https://github.com/SUSE/skuba/blob/master/docs/man/skuba-cluster-init.1.md

Could you please verify which one is correct and add this to the skuba docs?

**Comment by r0ckarong** [comment]
Also I can not find this in the current code base. That code has been moved so I can't verify the above commit.

**Comment by ereslibre** [comment]
> Could you please add this to the skuba docs?

Submitted https://github.com/SUSE/skuba/pull/730

**Comment by r0ckarong** [comment]
Fixed this in e8c92541cad1273f1a59967ebc0316fcc004f225

**Comment by jandubois** [comment]
@r0ckarong You missed an earlier mention of the option in the same file:

>In case you wish to use *unmodified CRI-O*,
use the `--strict-cap-defaults` option during the initial setup when you run `skuba cluster init`,
which will create the vanilla CRI-O configuration:

**Comment by r0ckarong** [comment]
> @r0ckarong You missed an earlier mention of the option in the same file:
> 
> > In case you wish to use _unmodified CRI-O_,
> > use the `--strict-cap-defaults` option during the initial setup when you run `skuba cluster init`,
> > which will create the vanilla CRI-O configuration:

@jandubois Where did you see this? I just checked and it's correct in the source code. If you found this on the documentation website then I need to trigger another rebuild.

**Comment by jandubois** [comment]
@r0ckarong I just looked at your change: https://github.com/SUSE/doc-caasp/pull/536/commits/6582e0edb7d247ec3d1ffddb254b43e13f708afe

It is missing the other mention of the parameter, but it has since been fixed by https://github.com/SUSE/doc-caasp/pull/536/commits/6582e0edb7d247ec3d1ffddb254b43e13f708afe

Sorry for not checking the state of `master` first! Everything looks fine now.
